apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x0oa6d6mc-go
  janus-idp.io/tekton: x0oa6d6mc-go
  backstage.io/kubernetes-id: x0oa6d6mc-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: x0oa6d6mc-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
